INSERT INTO DBMS (operator, system2, performance) VALUES ('Asoka', 'Fix San', 26);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Alphazap', 'Stim', 96);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Konklab', 'Namfix', 14);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Transcof', 'Quo Lux', 29);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Rank', 'Fixflex', 70);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Greenlam', 'Subin', 23);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Alpha', 'Regrant', 79);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Job', 'Stronghold', 9);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Alphazap', 'Hatity', 83);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Tampflex', 'Toughjoyfax', 37);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Alphazap', 'PostgreSQL', 50);
INSERT INTO DBMS (operator, system2, performance) VALUES ('Rank', 'Fixflex', 30);